syntax = "proto3";

package profiles.v1;

option csharp_namespace = "JacksonVeroneze.GrpcServer.Contracts.Profiles.V1";

import "profile_types.proto";
import "pagination_types.proto";

message ListProfilesRequest {
    optional string full_name = 1;
    optional ProfileGender gender = 2;
    optional string cpf = 3;
    optional ProfileStatus status = 4;
    optional PagedRequest pagination = 6;
}

message ListProfilesResponse {
    repeated Profile data = 1;
    PagedResponse pagination = 2;
}

message GetProfileRequest {
    string profile_id = 1;
}

message GetProfileResponse {
    Profile data = 1;
}

service ProfileQueryService {
    rpc ListProfiles(ListProfilesRequest) returns (ListProfilesResponse);
    rpc GetProfile(GetProfileRequest) returns (GetProfileResponse);
}
