syntax = "proto3";

package profiles.v1;

option csharp_namespace = "JacksonVeroneze.GrpcServer.Contracts.Profiles.V1";

enum OrderDirection {
    ORDER_UNSPECIFIED = 0;
    ORDER_ASCENDING = 1;
    ORDER_DESCENDING = 2;
}

message PagedRequest {
    optional string order_by = 1;
    optional OrderDirection order_direction = 2;
    optional int32 page_size = 3;
    optional string cursor = 4;
}

message PagedResponse {
    string order_by = 1;
    OrderDirection order_direction = 2;
    int32 page_size = 3;
    string cursor = 4;
}
