syntax = "proto3";

package profiles.v1;

option csharp_namespace = "JacksonVeroneze.GrpcServer.Contracts.Profiles.V1";

import "profiles/v1/profile_types.proto";

message CreateProfileRequest {
    string full_name = 1;
    string birth_date = 2;
    ProfileGender gender = 3;
    string cpf = 4;
}

message CreateProfileResponse {
    Profile profile = 1;
}

message ActivateProfileRequest {
    string profile_id = 1;
}

message ActivateProfileResponse {
}

message InactivateProfileRequest {
    string profile_id = 1;
}

message InactivateProfileResponse {
}

service ProfileCommandService {
    rpc CreateProfile(CreateProfileRequest) returns (CreateProfileResponse);
    rpc ActivateProfile(ActivateProfileRequest) returns (ActivateProfileResponse);
    rpc InactivateProfile(InactivateProfileRequest) returns (InactivateProfileResponse);
}
