syntax = "proto3";

import "google/protobuf/timestamp.proto";

option csharp_namespace = "JacksonVeroneze.NET.GRPCServer.Contracts.Profiles.v1";

package profiles.v1;

enum ProfileStatus {
    PROFILE_STATUS_UNSPECIFIED = 0;
    PROFILE_STATUS_ACTIVE = 1;
    PROFILE_STATUS_INACTIVE = 2;
    PROFILE_STATUS_PENDING_ACTIVATION = 3;
}

message Profile {
    string id = 1;
    string name = 2;
    string birthday = 3;
    string gender = 4;
    string cpf = 5;
    ProfileStatus status = 6;
    google.protobuf.Timestamp created_at = 7;
    google.protobuf.Timestamp updated_at = 8;
}
