<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>JacksonVeroneze.NET.GRPCServer.Contracts</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Core.Api" />
    <PackageReference Include="Grpc.Tools" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="protos\profiles\v1\pagination_types.proto" GrpcServices="None" ProtoRoot="protos"/>
    
    <Protobuf Include="protos\profiles\v1\profile_types.proto" GrpcServices="None" ProtoRoot="protos"/>

    <Protobuf Include="protos\profiles\v1\profile_command_service.proto" GrpcServices="Server" ProtoRoot="protos"/>
    <Protobuf Include="protos\profiles\v1\profile_query_service.proto" GrpcServices="Server" ProtoRoot="protos"/>
  </ItemGroup>

</Project>
