<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>JacksonVeroneze.NET.GRPCServer.Contracts</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore"/>
  </ItemGroup>
  
  <ItemGroup>
    <Protobuf Include="protos\orders\v1\common_types.proto" GrpcServices="None" ProtoRoot="protos" />
    <Protobuf Include="protos\orders\v1\order_types.proto" GrpcServices="None" ProtoRoot="protos" />

    <Protobuf Include="protos\orders\v1\order_command_service.proto" GrpcServices="Server" ProtoRoot="protos" />
    <Protobuf Include="protos\orders\v1\order_query_service.proto" GrpcServices="Server" ProtoRoot="protos" />
  </ItemGroup>

</Project>
