syntax = "proto3";

package profiles.v1;

option csharp_namespace = "JacksonVeroneze.GrpcServer.Contracts.Profiles.V1";

import "profiles/v1/profile_types.proto";

message CreateProfileRequest {
    string full_name = 1;
    string birth_date = 2;
    ProfileGender gender = 3;
    string cpf = 4;
    string email = 5;
    uint64 phone_number = 6;
    string mother_name = 7;
    string father_name = 8;
    string nationality = 9;
    string street = 10;
    int32 address_number = 11;
    string neighborhood = 12;
    string city = 13;
    string state = 14;
    string zip_code = 15;
    string country = 16;
    int32 dependents_count = 17;
    bool is_politically_exposed = 18;
    bool is_email_verified = 19;
    ProfileRiskLevel risk_level = 20;
    double latitude = 21;
    double longitude = 22;
}

message CreateProfileResponse {
    Profile profile = 1;
}

message ActivateProfileRequest {
    string profile_id = 1;
}

message ActivateProfileResponse {
}

message InactivateProfileRequest {
    string profile_id = 1;
}

message InactivateProfileResponse {
}

service ProfileCommandService {
    rpc CreateProfile(CreateProfileRequest) returns (CreateProfileResponse);
    rpc ActivateProfile(ActivateProfileRequest) returns (ActivateProfileResponse);
    rpc InactivateProfile(InactivateProfileRequest) returns (InactivateProfileResponse);
}
