syntax = "proto3";

package profiles.v1;

option csharp_namespace = "JacksonVeroneze.GrpcServer.Contracts.Profiles.V1";

enum ProfileStatus {
    PROFILE_STATUS_UNSPECIFIED = 0;
    PROFILE_STATUS_ACTIVE = 1;
    PROFILE_STATUS_INACTIVE = 2;
    PROFILE_STATUS_PENDING_ACTIVATION = 3;
}

enum ProfileGender {
    PROFILE_GENDER_UNSPECIFIED = 0;
    PROFILE_GENDER_MALE = 1;
    PROFILE_GENDER_FEMALE = 2;
    PROFILE_GENDER_OTHER = 3;
}

enum ProfileRiskLevel {
    PROFILE_RISK_LEVEL_UNSPECIFIED = 0;
    PROFILE_RISK_LEVEL_LOW = 1;
    PROFILE_RISK_LEVEL_MEDIUM = 2;
    PROFILE_RISK_LEVEL_HIGH = 3;
    PROFILE_RISK_LEVEL_CRITICAL = 4;
}

message Profile {
    string profile_id = 1;
    string full_name = 2;
    string birth_date = 3;
    ProfileGender gender = 4;
    string cpf = 5;
    ProfileStatus status = 6;
    string email = 7;
    uint64 phone_number = 8;
    string mother_name = 9;
    string father_name = 10;
    string nationality = 11;
    string street = 12;
    int32 address_number = 13;
    string neighborhood = 14;
    string city = 15;
    string state = 16;
    string zip_code = 17;
    string country = 18;
    int32 dependents_count = 19;
    bool is_politically_exposed = 20;
    bool is_email_verified = 21;
    ProfileRiskLevel risk_level = 22;
    double latitude = 23;
    double longitude = 24;
    optional int64 activated_on_unix_ms = 25;
    optional int64 inactivated_on_unix_ms = 26;
}
