<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>JacksonVeroneze.NET.GRPCServer.Domain</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JacksonVeroneze.NET.DomainObjects"/>
    <PackageReference Include="JacksonVeroneze.NET.Result"/>
  </ItemGroup>

</Project>
