syntax = "proto3";

import "google/protobuf/timestamp.proto";
import "orders/v1/common_types.proto";

option csharp_namespace = "JacksonVeroneze.NET.GRPCServer.Contracts.Orders.v1";

package orders.v1;

enum OrderStatus {
    ORDER_STATUS_UNSPECIFIED = 0;
    ORDER_STATUS_PENDING = 1;
    ORDER_STATUS_CONFIRMED = 2;
    ORDER_STATUS_CANCELLED = 3;
    ORDER_STATUS_REJECTED = 4;
}

message Order {
    string order_id = 1;
    string customer_id = 2;
    repeated OrderItem items = 3;
    OrderStatus status = 4;
    Money total_amount = 5;
    google.protobuf.Timestamp created_at = 6;
}

message OrderItem {
    string product_id = 1;
    string product_name = 2;
    int32 quantity = 3;
    Money unit_price = 4;
    Money total_price = 5;
}

message OrderSummary {
    string order_id = 1;
    string customer_id = 2;
    OrderStatus status = 3;
    Money total_amount = 4;
    google.protobuf.Timestamp created_at = 5;
}
