<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
        <EnablePackageVersionOverride>false</EnablePackageVersionOverride>
    </PropertyGroup>
    <ItemGroup Label="Analyzer">
        <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.25.0.139117"/>
        <PackageVersion Include="Microsoft.CodeAnalysis.BannedApiAnalyzers" Version="4.14.0"/>
        <PackageVersion Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.14.15"/>
        <PackageVersion Include="Meziantou.Analyzer" Version="3.0.87"/>
    </ItemGroup>
    <ItemGroup Label="All">
    </ItemGroup>
    <ItemGroup Label="Api">
        <PackageVersion Include="Grpc.AspNetCore" Version="2.80.0"/>
        <PackageVersion Include="Grpc.AspNetCore.Server.Reflection" Version="2.80.0"/>
        <PackageVersion Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1"/>
        <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8"/>
    </ItemGroup>
    <ItemGroup Label="Application">
        <PackageVersion Include="Mapster" Version="10.0.7"/>
        <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.8"/>
    </ItemGroup>
    <ItemGroup Label="Domain">
        <PackageVersion Include="JacksonVeroneze.NET.DomainObjects" Version="0.0.6"/>
        <PackageVersion Include="JacksonVeroneze.NET.Pagination" Version="1.1.8"/>
        <PackageVersion Include="JacksonVeroneze.NET.Result" Version="1.0.0"/>
    </ItemGroup>
    <ItemGroup Label="Infrastructure">
        <PackageVersion Include="CorrelationId" Version="3.0.1"/>
        <PackageVersion Include="Mapster.DependencyInjection" Version="10.0.7"/>
        <PackageVersion Include="JacksonVeroneze.NET.EntityFramework" Version="1.4.0"/>
        <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1"/>
        <PackageVersion Include="EFCore.NamingConventions" Version="10.0.1"/>
        <PackageVersion Include="Serilog.Settings.Configuration" Version="9.0.0"/>
        <PackageVersion Include="Serilog.Formatting.Compact" Version="3.0.0"/>
        <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8"/>
        <PackageVersion Include="Serilog.Sinks.Seq" Version="9.0.0"/>
        <PackageVersion Include="JacksonVeroneze.NET.Logging" Version="1.0.5"/>
        <PackageVersion Include="Hashids.net" Version="1.7.0"/>
        <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.15.3"/>
        <PackageVersion Include="OpenTelemetry.Instrumentation.Process" Version="1.11.0-beta.2"/>
        <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.15.2"/>
        <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.15.1"/>
        <PackageVersion Include="OpenTelemetry.Instrumentation.Runtime" Version="1.15.1"/>
        <PackageVersion Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" Version="1.0.0-beta.8"/>
        <PackageVersion Include="OpenTelemetry.Instrumentation.StackExchangeRedis" Version="1.0.0-rc9.12"/>
        <PackageVersion Include="OpenTelemetry.Exporter.Jaeger" Version="1.5.1"/>
        <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.15.3"/>
        <PackageVersion Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" Version="1.7.0-rc.1"/>
    </ItemGroup>
</Project>
