// <auto-generated />
using System;
using JacksonVeroneze.NET.GRPCServer.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JacksonVeroneze.NET.GRPCServer.Infrastructure.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    [Migration("20260611113412_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("profile")
                .HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("JacksonVeroneze.NET.GRPCServer.Domain.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActivatedOnUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("activated_on_utc");

                    b.Property<string>("AddressNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("address_number");

                    b.Property<string>("BirthCity")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("birth_city");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("birth_date");

                    b.Property<string>("BirthState")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("birth_state");

                    b.Property<string>("City")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("city");

                    b.Property<string>("Complement")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("complement");

                    b.Property<string>("Country")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT")
                        .HasColumnName("country");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("FatherName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("father_name");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("full_name");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER")
                        .HasColumnName("gender");

                    b.Property<DateTimeOffset?>("InactivatedOnUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("inactivated_on_utc");

                    b.Property<string>("MotherName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("mother_name");

                    b.Property<string>("Nationality")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT")
                        .HasColumnName("nationality");

                    b.Property<string>("Neighborhood")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("neighborhood");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone_number");

                    b.Property<string>("State")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<string>("Street")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("street");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("zip_code");

                    b.HasKey("Id")
                        .HasName("pk_profile");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("ix_profile_cpf");

                    b.ToTable("profile", "profile");
                });
#pragma warning restore 612, 618
        }
    }
}
