syntax = "proto3";
import "orders/v1/common_types.proto";
import "orders/v1/order_types.proto";

option csharp_namespace = "JacksonVeroneze.NET.GRPCServer.Api";

package orders.v1;

message ListOrdersRequest {
    optional string customer_id = 1;
    OrderStatus status = 2;
    int32 page_size = 3;
    string page_token = 4;
}

message ListOrdersResponse {
    repeated OrderSummary orders = 1;
    string next_page_token = 2;
}

service OrderQueryService {
    rpc ListOrders(ListOrdersRequest) returns (ListOrdersResponse);
}